title: ChAMELEON
tagline: Machine Learning, Optimization and Inference
description: >-
  Lectures and a summer school at the University of Houston on computational and mathematical
  methods in machine learning, inverse problems, and inference.
lang: en-US
author: Andreas Mang
logo: /files/logos/chameleonline-logo.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /files/logos/social-card.png

exclude:
  - README.md
